# Generated by Django 5.2.4 on 2025-07-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.PositiveBigIntegerField(max_length=15, unique=True)),
                ('monthly_salary', models.PositiveBigIntegerField()),
                ('approved_limit', models.PositiveBigIntegerField()),
                ('current_debt', models.PositiveBigIntegerField()),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('tenure', models.PositiveBigIntegerField(help_text='Tenure in month')),
                ('interest_rate', models.FloatField(help_text='Annual interest rate (%)')),
                ('monthly_installment', models.FloatField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('emis_paid_on_time', models.PositiveBigIntegerField(default=0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customer.customers')),
            ],
        ),
    ]
