# Generated by Django 5.2.4 on 2025-07-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
